# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

popC <- function(size, arr) {
    .Call(`_queueR_popC`, size, arr)
}

pushC <- function(size, arr, val) {
    .Call(`_queueR_pushC`, size, arr, val)
}

